<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KodeUnitAuditSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['kode_unit_audit' => '0000', 'nama_unit_audit' => 'PUSINFOWAS BPKP', 'jenis' => '1',],
            ['kode_unit_audit' => '0001', 'nama_unit_audit' => 'Majelis Permusyawaratan Rakyat Republik Indonesia', 'jenis' => '2',],
            ['kode_unit_audit' => '0002', 'nama_unit_audit' => 'Dewan Perwakilan Rakyat Republik Indonesia', 'jenis' => '2',],
            ['kode_unit_audit' => '0004', 'nama_unit_audit' => 'Badan Pemeriksa Keuangan Republik Indonesia', 'jenis' => '2',],
            ['kode_unit_audit' => '0005', 'nama_unit_audit' => 'Mahkamah Agung Republik Indonesia', 'jenis' => '2',],
            ['kode_unit_audit' => '0006', 'nama_unit_audit' => 'Kejaksaan Republik Indonesia', 'jenis' => '2',],
            ['kode_unit_audit' => '0007', 'nama_unit_audit' => 'Kementerian Sekretariat Negara', 'jenis' => '3',],
            ['kode_unit_audit' => '0010', 'nama_unit_audit' => 'Kementerian Dalam Negeri', 'jenis' => '3',],
            ['kode_unit_audit' => '0011', 'nama_unit_audit' => 'Kementerian Luar Negeri', 'jenis' => '3',],
            ['kode_unit_audit' => '0012', 'nama_unit_audit' => 'Kementerian  Pertahanan', 'jenis' => '3',],
            ['kode_unit_audit' => '0013', 'nama_unit_audit' => 'Kementerian Hukum dan Hak Asasi Manusia', 'jenis' => '3',],
            ['kode_unit_audit' => '0015', 'nama_unit_audit' => 'Kementerian Keuangan', 'jenis' => '3',],
            ['kode_unit_audit' => '0018', 'nama_unit_audit' => 'Kementerian Pertanian', 'jenis' => '3',],
            ['kode_unit_audit' => '0019', 'nama_unit_audit' => 'Kementerian Perindustrian', 'jenis' => '3',],
            ['kode_unit_audit' => '0020', 'nama_unit_audit' => 'Kementerian Energi dan Sumber Daya Mineral', 'jenis' => '3',],
            ['kode_unit_audit' => '0022', 'nama_unit_audit' => 'Kementerian Perhubungan', 'jenis' => '3',],
            ['kode_unit_audit' => '0023', 'nama_unit_audit' => 'Kementerian Pendidikan dan Kebudayaan', 'jenis' => '3',],
            ['kode_unit_audit' => '0024', 'nama_unit_audit' => 'Kementerian Kesehatan', 'jenis' => '3',],
            ['kode_unit_audit' => '0025', 'nama_unit_audit' => 'Kementerian Agama', 'jenis' => '3',],
            ['kode_unit_audit' => '0026', 'nama_unit_audit' => 'Kementerian Ketenagakerjaan', 'jenis' => '3',],
            ['kode_unit_audit' => '0027', 'nama_unit_audit' => 'Kementerian Sosial', 'jenis' => '3',],
            ['kode_unit_audit' => '0029', 'nama_unit_audit' => 'Kementerian Lingkungan Hidup dan Kehutanan', 'jenis' => '3',],
            ['kode_unit_audit' => '0032', 'nama_unit_audit' => 'Kementerian Kelautan dan Perikanan', 'jenis' => '3',],
            ['kode_unit_audit' => '0033', 'nama_unit_audit' => 'Kementerian Pekerjaan Umum dan Perumahan Rakyat', 'jenis' => '3',],
            ['kode_unit_audit' => '0034', 'nama_unit_audit' => 'Kementerian Koordinator Bidang Politik, Hukum, dan Keamanan', 'jenis' => '3',],
            ['kode_unit_audit' => '0035', 'nama_unit_audit' => 'Kementerian Koordinator Bidang Perekonomian', 'jenis' => '3',],
            ['kode_unit_audit' => '0036', 'nama_unit_audit' => 'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', 'jenis' => '3',],
            ['kode_unit_audit' => '0040', 'nama_unit_audit' => 'Kementerian Pariwisata dan Ekonomi Kreatif/ Badan Pariwisata dan Ekonomi Kreatif', 'jenis' => '3',],
            ['kode_unit_audit' => '0041', 'nama_unit_audit' => 'Kementerian Badan Usaha Milik Negara', 'jenis' => '3',],
            ['kode_unit_audit' => '0042', 'nama_unit_audit' => 'Kementerian Riset dan Teknologi/ Badan Riset dan Inovasi Nasional', 'jenis' => '3',],
            ['kode_unit_audit' => '0044', 'nama_unit_audit' => 'Kementerian Koperasi dan Usaha Kecil dan Menengah', 'jenis' => '3',],
            ['kode_unit_audit' => '0047', 'nama_unit_audit' => 'Kementerian Pemberdayaan Perempuan dan Perlindungan Anak', 'jenis' => '3',],
            ['kode_unit_audit' => '0048', 'nama_unit_audit' => 'Kementerian Pendayagunaan Aparatur Negara dan Reformasi Birokrasi', 'jenis' => '3',],
            ['kode_unit_audit' => '0050', 'nama_unit_audit' => 'Badan Intelijen Negara', 'jenis' => '4',],
            ['kode_unit_audit' => '0051', 'nama_unit_audit' => 'Badan Siber dan Sandi Negara', 'jenis' => '4',],
            ['kode_unit_audit' => '0052', 'nama_unit_audit' => 'Dewan Ketahanan Nasional', 'jenis' => '4',],
            ['kode_unit_audit' => '0054', 'nama_unit_audit' => 'Badan Pusat Statistik', 'jenis' => '4',],
            ['kode_unit_audit' => '0055', 'nama_unit_audit' => 'Kementerian Perencanaan Pembangunan Nasional/Badan Perencanaan Pembangunan Nasional', 'jenis' => '3',],
            ['kode_unit_audit' => '0056', 'nama_unit_audit' => 'Kementerian Agraria dan Tata Ruang/Badan Pertanahan Nasional', 'jenis' => '3',],
            ['kode_unit_audit' => '0057', 'nama_unit_audit' => 'Perpustakaan Nasional Republik Indonesia', 'jenis' => '4',],
            ['kode_unit_audit' => '0059', 'nama_unit_audit' => 'Kementerian Komunikasi dan Informatika', 'jenis' => '3',],
            ['kode_unit_audit' => '0060', 'nama_unit_audit' => 'Kepolisian Negara Republik Indonesia', 'jenis' => '4',],
            ['kode_unit_audit' => '0063', 'nama_unit_audit' => 'Badan Pengawasan Obat dan Makanan', 'jenis' => '4',],
            ['kode_unit_audit' => '0064', 'nama_unit_audit' => 'Lembaga Ketahanan Nasional', 'jenis' => '4',],
            ['kode_unit_audit' => '0065', 'nama_unit_audit' => 'Badan Koordinasi Penanaman Modal', 'jenis' => '4',],
            ['kode_unit_audit' => '0066', 'nama_unit_audit' => 'Badan Narkotika Nasional', 'jenis' => '4',],
            ['kode_unit_audit' => '0067', 'nama_unit_audit' => 'Kementerian Desa, Pembangunan Daerah Tertinggal, dan Transmigrasi', 'jenis' => '3',],
            ['kode_unit_audit' => '0068', 'nama_unit_audit' => 'Badan Kependudukan dan Keluarga Berencana Nasional', 'jenis' => '4',],
            ['kode_unit_audit' => '0074', 'nama_unit_audit' => 'Komisi Nasional Hak Asasi Manusia', 'jenis' => '5',],
            ['kode_unit_audit' => '0075', 'nama_unit_audit' => 'Badan Meteorologi, Klimatologi, dan Geofisika', 'jenis' => '4',],
            ['kode_unit_audit' => '0076', 'nama_unit_audit' => 'Komisi Pemilihan Umum', 'jenis' => '5',],
            ['kode_unit_audit' => '0077', 'nama_unit_audit' => 'Mahkamah Konstitusi Republik Indonesia', 'jenis' => '2',],
            ['kode_unit_audit' => '0078', 'nama_unit_audit' => 'Pusat Pelaporan dan Analisis Transaksi Keuangan', 'jenis' => '4',],
            ['kode_unit_audit' => '0079', 'nama_unit_audit' => 'Lembaga Ilmu Pengetahuan Indonesia', 'jenis' => '4',],
            ['kode_unit_audit' => '0080', 'nama_unit_audit' => 'Badan Tenaga Nuklir Nasional', 'jenis' => '4',],
            ['kode_unit_audit' => '0081', 'nama_unit_audit' => 'Badan Pengkajian dan Penerapan Teknologi', 'jenis' => '4',],
            ['kode_unit_audit' => '0082', 'nama_unit_audit' => 'Lembaga Penerbangan dan Antariksa Nasional', 'jenis' => '4',],
            ['kode_unit_audit' => '0083', 'nama_unit_audit' => 'Badan Informasi Geospasial', 'jenis' => '4',],
            ['kode_unit_audit' => '0084', 'nama_unit_audit' => 'Badan Standardisasi Nasional', 'jenis' => '4',],
            ['kode_unit_audit' => '0085', 'nama_unit_audit' => 'Badan Pengawas Tenaga Nuklir', 'jenis' => '4',],
            ['kode_unit_audit' => '0086', 'nama_unit_audit' => 'Lembaga Administrasi Negara', 'jenis' => '4',],
            ['kode_unit_audit' => '0087', 'nama_unit_audit' => 'Arsip Nasional Republik Indonesia', 'jenis' => '4',],
            ['kode_unit_audit' => '0088', 'nama_unit_audit' => 'Badan Kepegawaian Negara', 'jenis' => '4',],
            ['kode_unit_audit' => '0089', 'nama_unit_audit' => 'Badan Pengawasan Keuangan dan Pembangunan', 'jenis' => '4',],
            ['kode_unit_audit' => '0090', 'nama_unit_audit' => 'Kementerian Perdagangan', 'jenis' => '3',],
            ['kode_unit_audit' => '0092', 'nama_unit_audit' => 'Kementerian Pemuda dan Olahraga', 'jenis' => '3',],
            ['kode_unit_audit' => '0093', 'nama_unit_audit' => 'Komisi Pemberantasan Korupsi', 'jenis' => '5',],
            ['kode_unit_audit' => '0095', 'nama_unit_audit' => 'Dewan Perwakilan Daerah', 'jenis' => '2',],
            ['kode_unit_audit' => '0100', 'nama_unit_audit' => 'Komisi Yudisial Republik Indonesia', 'jenis' => '5',],
            ['kode_unit_audit' => '0103', 'nama_unit_audit' => 'Badan Nasional Penanggulangan Bencana', 'jenis' => '4',],
            ['kode_unit_audit' => '0104', 'nama_unit_audit' => 'Badan Nasional Penempatan dan Perlindungan Tenaga Kerja Indonesia', 'jenis' => '4',],
            ['kode_unit_audit' => '0106', 'nama_unit_audit' => 'Lembaga Kebijakan Pengadaan Barang/ Jasa Pemerintah', 'jenis' => '4',],
            ['kode_unit_audit' => '0107', 'nama_unit_audit' => 'Badan Nasional Pencarian dan Pertolongan', 'jenis' => '4',],
            ['kode_unit_audit' => '0108', 'nama_unit_audit' => 'Komisi Pengawasan Persaingan Usaha', 'jenis' => '5',],
            ['kode_unit_audit' => '0109', 'nama_unit_audit' => 'Badan Pengembangan Wilayah Suramadu', 'jenis' => '4',],
            ['kode_unit_audit' => '0110', 'nama_unit_audit' => 'Ombudsman Republik Indonesia', 'jenis' => '2',],
            ['kode_unit_audit' => '0111', 'nama_unit_audit' => 'Badan Nasional Pengelola Perbatasan', 'jenis' => '4',],
            ['kode_unit_audit' => '0112', 'nama_unit_audit' => 'Badan Pengusahaan Kawasan Perdagangan Bebas dan Pelabuhan Bebas Batam', 'jenis' => '4',],
            ['kode_unit_audit' => '0113', 'nama_unit_audit' => 'Badan Nasional Penanggulangan Terorisme', 'jenis' => '4',],
            ['kode_unit_audit' => '0114', 'nama_unit_audit' => 'Sekretariat Kabinet', 'jenis' => '2',],
            ['kode_unit_audit' => '0115', 'nama_unit_audit' => 'Badan Pengawas Pemilihan  Umum', 'jenis' => '4',],
            ['kode_unit_audit' => '0116', 'nama_unit_audit' => 'Lembaga Penyiaran Publik Radio Republik Indonesia', 'jenis' => '4',],
            ['kode_unit_audit' => '0117', 'nama_unit_audit' => 'Lembaga Penyiaran Publik Televisi Republik Indonesia', 'jenis' => '4',],
            ['kode_unit_audit' => '0118', 'nama_unit_audit' => 'Badan Pengusahaan  Kawasan  Perdagangan  Bebas dan Pelabuhan Bebas Sabang', 'jenis' => '4',],
            ['kode_unit_audit' => '0119', 'nama_unit_audit' => 'Badan Keamanan Laut', 'jenis' => '4',],
            ['kode_unit_audit' => '0120', 'nama_unit_audit' => 'Kementerian Koordinator Bidang Kemaritiman dan Investasi', 'jenis' => '3',],
            ['kode_unit_audit' => '0122', 'nama_unit_audit' => 'Badan Pembinaan Ideologi Pancasila', 'jenis' => '4',],
            ['kode_unit_audit' => '1100', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI ACEH', 'jenis' => '1',],
            ['kode_unit_audit' => '1101', 'nama_unit_audit' => 'INSPEKTORAT KAB. ACEH SELATAN', 'jenis' => '0',],
            ['kode_unit_audit' => '1102', 'nama_unit_audit' => 'INSPEKTORAT KAB. ACEH TENGGARA', 'jenis' => '0',],
            ['kode_unit_audit' => '1103', 'nama_unit_audit' => 'INSPEKTORAT KAB. ACEH TIMUR', 'jenis' => '0',],
            ['kode_unit_audit' => '1104', 'nama_unit_audit' => 'INSPEKTORAT KAB. ACEH TENGAH', 'jenis' => '0',],
            ['kode_unit_audit' => '1105', 'nama_unit_audit' => 'INSPEKTORAT KAB. ACEH BARAT', 'jenis' => '0',],
            ['kode_unit_audit' => '1106', 'nama_unit_audit' => 'INSPEKTORAT KAB. ACEH BESAR', 'jenis' => '0',],
            ['kode_unit_audit' => '1107', 'nama_unit_audit' => 'INSPEKTORAT KAB. PIDIE', 'jenis' => '0',],
            ['kode_unit_audit' => '1108', 'nama_unit_audit' => 'INSPEKTORAT KAB. ACEH UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '1109', 'nama_unit_audit' => 'INSPEKTORAT KAB. SIMEULUE', 'jenis' => '0',],
            ['kode_unit_audit' => '1110', 'nama_unit_audit' => 'INSPEKTORAT KAB. ACEH SINGKIL', 'jenis' => '0',],
            ['kode_unit_audit' => '1111', 'nama_unit_audit' => 'INSPEKTORAT KAB. BIREUEN', 'jenis' => '0',],
            ['kode_unit_audit' => '1112', 'nama_unit_audit' => 'INSPEKTORAT KAB. ACEH BARAT DAYA', 'jenis' => '0',],
            ['kode_unit_audit' => '1113', 'nama_unit_audit' => 'INSPEKTORAT KAB. GAYO LUES', 'jenis' => '0',],
            ['kode_unit_audit' => '1114', 'nama_unit_audit' => 'INSPEKTORAT KAB. ACEH JAYA', 'jenis' => '0',],
            ['kode_unit_audit' => '1115', 'nama_unit_audit' => 'INSPEKTORAT KAB. NAGAN RAYA', 'jenis' => '0',],
            ['kode_unit_audit' => '1116', 'nama_unit_audit' => 'INSPEKTORAT KAB. ACEH TAMIANG', 'jenis' => '0',],
            ['kode_unit_audit' => '1117', 'nama_unit_audit' => 'INSPEKTORAT KAB. BENER MERIAH', 'jenis' => '0',],
            ['kode_unit_audit' => '1118', 'nama_unit_audit' => 'INSPEKTORAT KAB. PIDIE JAYA', 'jenis' => '0',],
            ['kode_unit_audit' => '1171', 'nama_unit_audit' => 'INSPEKTORAT KOTA BANDA ACEH', 'jenis' => '0',],
            ['kode_unit_audit' => '1172', 'nama_unit_audit' => 'INSPEKTORAT KOTA SABANG', 'jenis' => '0',],
            ['kode_unit_audit' => '1173', 'nama_unit_audit' => 'INSPEKTORAT KOTA LHOKSEUMAWE', 'jenis' => '0',],
            ['kode_unit_audit' => '1174', 'nama_unit_audit' => 'INSPEKTORAT KOTA LANGSA', 'jenis' => '0',],
            ['kode_unit_audit' => '1175', 'nama_unit_audit' => 'INSPEKTORAT KOTA SUBULUSSALAM', 'jenis' => '0',],
            ['kode_unit_audit' => '1200', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI SUMATERA UTARA', 'jenis' => '1',],
            ['kode_unit_audit' => '1201', 'nama_unit_audit' => 'INSPEKTORAT KAB. TAPANULI TENGAH', 'jenis' => '0',],
            ['kode_unit_audit' => '1202', 'nama_unit_audit' => 'INSPEKTORAT KAB. TAPANULI UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '1203', 'nama_unit_audit' => 'INSPEKTORAT KAB. TAPANULI SELATAN', 'jenis' => '0',],
            ['kode_unit_audit' => '1204', 'nama_unit_audit' => 'INSPEKTORAT KAB. NIAS', 'jenis' => '0',],
            ['kode_unit_audit' => '1205', 'nama_unit_audit' => 'INSPEKTORAT KAB. LANGKAT', 'jenis' => '0',],
            ['kode_unit_audit' => '1206', 'nama_unit_audit' => 'INSPEKTORAT KAB. KARO', 'jenis' => '0',],
            ['kode_unit_audit' => '1207', 'nama_unit_audit' => 'INSPEKTORAT KAB. DELI SERDANG', 'jenis' => '0',],
            ['kode_unit_audit' => '1208', 'nama_unit_audit' => 'INSPEKTORAT KAB. SIMALUNGUN', 'jenis' => '0',],
            ['kode_unit_audit' => '1209', 'nama_unit_audit' => 'INSPEKTORAT KAB. ASAHAN', 'jenis' => '0',],
            ['kode_unit_audit' => '1210', 'nama_unit_audit' => 'INSPEKTORAT KAB. LABUHANBATU', 'jenis' => '0',],
            ['kode_unit_audit' => '1211', 'nama_unit_audit' => 'INSPEKTORAT KAB. DAIRI', 'jenis' => '0',],
            ['kode_unit_audit' => '1212', 'nama_unit_audit' => 'INSPEKTORAT KAB. TOBA SAMOSIR', 'jenis' => '0',],
            ['kode_unit_audit' => '1213', 'nama_unit_audit' => 'INSPEKTORAT KAB. MANDAILING NATAL', 'jenis' => '0',],
            ['kode_unit_audit' => '1214', 'nama_unit_audit' => 'INSPEKTORAT KAB. NIAS SELATAN', 'jenis' => '0',],
            ['kode_unit_audit' => '1215', 'nama_unit_audit' => 'INSPEKTORAT KAB. PAKPAK BHARAT', 'jenis' => '0',],
            ['kode_unit_audit' => '1216', 'nama_unit_audit' => 'INSPEKTORAT KAB. HUMBANG HASUNDUTAN', 'jenis' => '0',],
            ['kode_unit_audit' => '1217', 'nama_unit_audit' => 'INSPEKTORAT KAB. SAMOSIR', 'jenis' => '0',],
            ['kode_unit_audit' => '1218', 'nama_unit_audit' => 'INSPEKTORAT KAB. SERDANG BEDAGA', 'jenis' => '0',],
            ['kode_unit_audit' => '1219', 'nama_unit_audit' => 'INSPEKTORAT KAB. BATU BARA', 'jenis' => '0',],
            ['kode_unit_audit' => '1220', 'nama_unit_audit' => 'INSPEKTORAT KAB. PADANG LAWAS UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '1221', 'nama_unit_audit' => 'INSPEKTORAT KAB. PADANG LAWAS', 'jenis' => '0',],
            ['kode_unit_audit' => '1222', 'nama_unit_audit' => 'INSPEKTORAT KAB. LABUHANBATU SELATAN', 'jenis' => '0',],
            ['kode_unit_audit' => '1223', 'nama_unit_audit' => 'INSPEKTORAT KAB. LABUHANBATU UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '1224', 'nama_unit_audit' => 'INSPEKTORAT KAB. NIAS UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '1225', 'nama_unit_audit' => 'INSPEKTORAT KAB. NIAS BARAT', 'jenis' => '0',],
            ['kode_unit_audit' => '1271', 'nama_unit_audit' => 'INSPEKTORAT KOTA MEDAN', 'jenis' => '0',],
            ['kode_unit_audit' => '1272', 'nama_unit_audit' => 'INSPEKTORAT KOTA PEMATANGSIANTAR', 'jenis' => '0',],
            ['kode_unit_audit' => '1273', 'nama_unit_audit' => 'INSPEKTORAT KOTA SIBOLGA', 'jenis' => '0',],
            ['kode_unit_audit' => '1274', 'nama_unit_audit' => 'INSPEKTORAT KOTA TANJUNG BALAI', 'jenis' => '0',],
            ['kode_unit_audit' => '1275', 'nama_unit_audit' => 'INSPEKTORAT KOTA BINJAI', 'jenis' => '0',],
            ['kode_unit_audit' => '1276', 'nama_unit_audit' => 'INSPEKTORAT KOTA TEBING TINGGI', 'jenis' => '0',],
            ['kode_unit_audit' => '1277', 'nama_unit_audit' => 'INSPEKTORAT KOTA PADANGSIDIMPUAN', 'jenis' => '0',],
            ['kode_unit_audit' => '1278', 'nama_unit_audit' => 'INSPEKTORAT KOTA GUNUNGSITOLI', 'jenis' => '0',],
            ['kode_unit_audit' => '1300', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI SUMATERA BARAT', 'jenis' => '1',],
            ['kode_unit_audit' => '1301', 'nama_unit_audit' => 'INSPEKTORAT KAB. PESISIR SELATAN', 'jenis' => '0',],
            ['kode_unit_audit' => '1302', 'nama_unit_audit' => 'INSPEKTORAT KAB. SOLOK', 'jenis' => '0',],
            ['kode_unit_audit' => '1303', 'nama_unit_audit' => 'INSPEKTORAT KAB. SIJUNJUNG', 'jenis' => '0',],
            ['kode_unit_audit' => '1304', 'nama_unit_audit' => 'INSPEKTORAT KAB. TANAH DATAR', 'jenis' => '0',],
            ['kode_unit_audit' => '1305', 'nama_unit_audit' => 'INSPEKTORAT KAB. PADANG PARIAMAN', 'jenis' => '0',],
            ['kode_unit_audit' => '1306', 'nama_unit_audit' => 'INSPEKTORAT KAB. AGAM', 'jenis' => '0',],
            ['kode_unit_audit' => '1307', 'nama_unit_audit' => 'INSPEKTORAT KAB. LIMA PULUH KOTA', 'jenis' => '0',],
            ['kode_unit_audit' => '1308', 'nama_unit_audit' => 'INSPEKTORAT KAB. PASAMAN', 'jenis' => '0',],
            ['kode_unit_audit' => '1309', 'nama_unit_audit' => 'INSPEKTORAT KAB. KEPULAUAN MENTAWA', 'jenis' => '0',],
            ['kode_unit_audit' => '1310', 'nama_unit_audit' => 'INSPEKTORAT KAB. DHARMASRAYA', 'jenis' => '0',],
            ['kode_unit_audit' => '1311', 'nama_unit_audit' => 'INSPEKTORAT KAB. SOLOK SELATAN', 'jenis' => '0',],
            ['kode_unit_audit' => '1312', 'nama_unit_audit' => 'INSPEKTORAT KAB. PASAMAN BARAT', 'jenis' => '0',],
            ['kode_unit_audit' => '1371', 'nama_unit_audit' => 'INSPEKTORAT KOTA PADANG', 'jenis' => '0',],
            ['kode_unit_audit' => '1372', 'nama_unit_audit' => 'INSPEKTORAT KOTA SOLOK', 'jenis' => '0',],
            ['kode_unit_audit' => '1373', 'nama_unit_audit' => 'INSPEKTORAT KOTA SAWAHLUNTO', 'jenis' => '0',],
            ['kode_unit_audit' => '1374', 'nama_unit_audit' => 'INSPEKTORAT KOTA PADANG PANJANG', 'jenis' => '0',],
            ['kode_unit_audit' => '1375', 'nama_unit_audit' => 'INSPEKTORAT KOTA BUKITTINGGI', 'jenis' => '0',],
            ['kode_unit_audit' => '1376', 'nama_unit_audit' => 'INSPEKTORAT KOTA PAYAKUMBUH', 'jenis' => '0',],
            ['kode_unit_audit' => '1377', 'nama_unit_audit' => 'INSPEKTORAT KOTA PARIAMAN', 'jenis' => '0',],
            ['kode_unit_audit' => '1400', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI RIAU', 'jenis' => '1',],
            ['kode_unit_audit' => '1401', 'nama_unit_audit' => 'INSPEKTORAT KAB. KAMPAR', 'jenis' => '0',],
            ['kode_unit_audit' => '1402', 'nama_unit_audit' => 'INSPEKTORAT KAB. INDRAGIRI HULU', 'jenis' => '0',],
            ['kode_unit_audit' => '1403', 'nama_unit_audit' => 'INSPEKTORAT KAB. BENGKALIS', 'jenis' => '0',],
            ['kode_unit_audit' => '1404', 'nama_unit_audit' => 'INSPEKTORAT KAB. INDRAGIRI HILIR', 'jenis' => '0',],
            ['kode_unit_audit' => '1405', 'nama_unit_audit' => 'INSPEKTORAT KAB. PELALAWAN', 'jenis' => '0',],
            ['kode_unit_audit' => '1406', 'nama_unit_audit' => 'INSPEKTORAT KAB. ROKAN HULU', 'jenis' => '0',],
            ['kode_unit_audit' => '1407', 'nama_unit_audit' => 'INSPEKTORAT KAB. ROKAN HILIR', 'jenis' => '0',],
            ['kode_unit_audit' => '1408', 'nama_unit_audit' => 'INSPEKTORAT KAB. SIAK', 'jenis' => '0',],
            ['kode_unit_audit' => '1409', 'nama_unit_audit' => 'INSPEKTORAT KAB. KUANTAN SINGINGI', 'jenis' => '0',],
            ['kode_unit_audit' => '1410', 'nama_unit_audit' => 'INSPEKTORAT KAB. KEPULAUAN MERANTI', 'jenis' => '0',],
            ['kode_unit_audit' => '1471', 'nama_unit_audit' => 'INSPEKTORAT KOTA PEKANBARU', 'jenis' => '0',],
            ['kode_unit_audit' => '1472', 'nama_unit_audit' => 'INSPEKTORAT KOTA DUMAI', 'jenis' => '0',],
            ['kode_unit_audit' => '1500', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI JAMBI', 'jenis' => '1',],
            ['kode_unit_audit' => '1501', 'nama_unit_audit' => 'INSPEKTORAT KAB. KERINCI', 'jenis' => '0',],
            ['kode_unit_audit' => '1502', 'nama_unit_audit' => 'INSPEKTORAT KAB. MERANGIN', 'jenis' => '0',],
            ['kode_unit_audit' => '1503', 'nama_unit_audit' => 'INSPEKTORAT KAB. SAROLANGUN', 'jenis' => '0',],
            ['kode_unit_audit' => '1504', 'nama_unit_audit' => 'INSPEKTORAT KAB. BATANGHARI', 'jenis' => '0',],
            ['kode_unit_audit' => '1505', 'nama_unit_audit' => 'INSPEKTORAT KAB. MUARO JAMBI', 'jenis' => '0',],
            ['kode_unit_audit' => '1506', 'nama_unit_audit' => 'INSPEKTORAT KAB. TANJUNG JABUNG BARAT', 'jenis' => '0',],
            ['kode_unit_audit' => '1507', 'nama_unit_audit' => 'INSPEKTORAT KAB. TANJUNG JABUNG TIMUR', 'jenis' => '0',],
            ['kode_unit_audit' => '1508', 'nama_unit_audit' => 'INSPEKTORAT KAB. BUNGO', 'jenis' => '0',],
            ['kode_unit_audit' => '1509', 'nama_unit_audit' => 'INSPEKTORAT KAB. TEBO', 'jenis' => '0',],
            ['kode_unit_audit' => '1571', 'nama_unit_audit' => 'INSPEKTORAT KOTA JAMBI', 'jenis' => '0',],
            ['kode_unit_audit' => '1572', 'nama_unit_audit' => 'INSPEKTORAT KOTA SUNGAI PENUH', 'jenis' => '0',],
            ['kode_unit_audit' => '1600', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI SUMATERA SELATAN', 'jenis' => '1',],
            ['kode_unit_audit' => '1601', 'nama_unit_audit' => 'INSPEKTORAT KAB. OGAN KOMERING ULU', 'jenis' => '0',],
            ['kode_unit_audit' => '1602', 'nama_unit_audit' => 'INSPEKTORAT KAB. OGAN KOMERING ILIR', 'jenis' => '0',],
            ['kode_unit_audit' => '1603', 'nama_unit_audit' => 'INSPEKTORAT KAB. MUARA ENIM', 'jenis' => '0',],
            ['kode_unit_audit' => '1604', 'nama_unit_audit' => 'INSPEKTORAT KAB. LAHAT', 'jenis' => '0',],
            ['kode_unit_audit' => '1605', 'nama_unit_audit' => 'INSPEKTORAT KAB. MUSI RAWAS', 'jenis' => '0',],
            ['kode_unit_audit' => '1606', 'nama_unit_audit' => 'INSPEKTORAT KAB. MUSI BANYUASIN', 'jenis' => '0',],
            ['kode_unit_audit' => '1607', 'nama_unit_audit' => 'INSPEKTORAT KAB. BANYUASIN', 'jenis' => '0',],
            ['kode_unit_audit' => '1608', 'nama_unit_audit' => 'INSPEKTORAT KAB. OGAN KOMERING ULU TIMUR', 'jenis' => '0',],
            ['kode_unit_audit' => '1609', 'nama_unit_audit' => 'INSPEKTORAT KAB. OGAN KOMERING ULU SELATAN', 'jenis' => '0',],
            ['kode_unit_audit' => '1610', 'nama_unit_audit' => 'INSPEKTORAT KAB. OGAN ILIR', 'jenis' => '0',],
            ['kode_unit_audit' => '1611', 'nama_unit_audit' => 'INSPEKTORAT KAB. EMPAT LAWANG', 'jenis' => '0',],
            ['kode_unit_audit' => '1612', 'nama_unit_audit' => 'INSPEKTORAT KAB. PENUKAL ABAB LEMATANG ILIR', 'jenis' => '0',],
            ['kode_unit_audit' => '1613', 'nama_unit_audit' => 'INSPEKTORAT KAB. MUSI RAWAS UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '1671', 'nama_unit_audit' => 'INSPEKTORAT KOTA PALEMBANG', 'jenis' => '0',],
            ['kode_unit_audit' => '1672', 'nama_unit_audit' => 'INSPEKTORAT KOTA PAGAR ALAM', 'jenis' => '0',],
            ['kode_unit_audit' => '1673', 'nama_unit_audit' => 'INSPEKTORAT KOTA LUBUK LINGGAU', 'jenis' => '0',],
            ['kode_unit_audit' => '1674', 'nama_unit_audit' => 'INSPEKTORAT KOTA PRABUMULIH', 'jenis' => '0',],
            ['kode_unit_audit' => '1700', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI BENGKULU', 'jenis' => '1',],
            ['kode_unit_audit' => '1701', 'nama_unit_audit' => 'INSPEKTORAT KAB. BENGKULU SELATAN', 'jenis' => '0',],
            ['kode_unit_audit' => '1702', 'nama_unit_audit' => 'INSPEKTORAT KAB. REJANG LEBONG', 'jenis' => '0',],
            ['kode_unit_audit' => '1703', 'nama_unit_audit' => 'INSPEKTORAT KAB. BENGKULU UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '1704', 'nama_unit_audit' => 'INSPEKTORAT KAB. KAUR', 'jenis' => '0',],
            ['kode_unit_audit' => '1705', 'nama_unit_audit' => 'INSPEKTORAT KAB. SELUMA', 'jenis' => '0',],
            ['kode_unit_audit' => '1706', 'nama_unit_audit' => 'INSPEKTORAT KAB. MUKO MUKO', 'jenis' => '0',],
            ['kode_unit_audit' => '1707', 'nama_unit_audit' => 'INSPEKTORAT KAB. LEBONG', 'jenis' => '0',],
            ['kode_unit_audit' => '1708', 'nama_unit_audit' => 'INSPEKTORAT KAB. KEPAHIANG', 'jenis' => '0',],
            ['kode_unit_audit' => '1709', 'nama_unit_audit' => 'INSPEKTORAT KAB. BENGKULU TENGAH', 'jenis' => '0',],
            ['kode_unit_audit' => '1771', 'nama_unit_audit' => 'INSPEKTORAT KOTA BENGKULU', 'jenis' => '0',],
            ['kode_unit_audit' => '1800', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI LAMPUNG', 'jenis' => '1',],
            ['kode_unit_audit' => '1801', 'nama_unit_audit' => 'INSPEKTORAT KAB. LAMPUNG SELATAN', 'jenis' => '0',],
            ['kode_unit_audit' => '1802', 'nama_unit_audit' => 'INSPEKTORAT KAB. LAMPUNG TENGAH', 'jenis' => '0',],
            ['kode_unit_audit' => '1803', 'nama_unit_audit' => 'INSPEKTORAT KAB. LAMPUNG UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '1804', 'nama_unit_audit' => 'INSPEKTORAT KAB. LAMPUNG BARAT', 'jenis' => '0',],
            ['kode_unit_audit' => '1805', 'nama_unit_audit' => 'INSPEKTORAT KAB. TULANG BAWANG', 'jenis' => '0',],
            ['kode_unit_audit' => '1806', 'nama_unit_audit' => 'INSPEKTORAT KAB. TANGGAMUS', 'jenis' => '0',],
            ['kode_unit_audit' => '1807', 'nama_unit_audit' => 'INSPEKTORAT KAB. LAMPUNG TIMUR', 'jenis' => '0',],
            ['kode_unit_audit' => '1808', 'nama_unit_audit' => 'INSPEKTORAT KAB. WAY KANAN', 'jenis' => '0',],
            ['kode_unit_audit' => '1809', 'nama_unit_audit' => 'INSPEKTORAT KAB. PESAWARAN', 'jenis' => '0',],
            ['kode_unit_audit' => '1810', 'nama_unit_audit' => 'INSPEKTORAT KAB. PRINGSEWU', 'jenis' => '0',],
            ['kode_unit_audit' => '1811', 'nama_unit_audit' => 'INSPEKTORAT KAB. MESUJI', 'jenis' => '0',],
            ['kode_unit_audit' => '1812', 'nama_unit_audit' => 'INSPEKTORAT KAB. TULANG BAWANG BARAT', 'jenis' => '0',],
            ['kode_unit_audit' => '1813', 'nama_unit_audit' => 'INSPEKTORAT KAB. PESISIR BARAT', 'jenis' => '0',],
            ['kode_unit_audit' => '1871', 'nama_unit_audit' => 'INSPEKTORAT KOTA BANDAR LAMPUNG', 'jenis' => '0',],
            ['kode_unit_audit' => '1872', 'nama_unit_audit' => 'INSPEKTORAT KOTA METRO', 'jenis' => '0',],
            ['kode_unit_audit' => '1900', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI KEPULAUAN BANGKA BELITUNG', 'jenis' => '1',],
            ['kode_unit_audit' => '1901', 'nama_unit_audit' => 'INSPEKTORAT KAB. BANGKA', 'jenis' => '0',],
            ['kode_unit_audit' => '1902', 'nama_unit_audit' => 'INSPEKTORAT KAB. BELITUNG', 'jenis' => '0',],
            ['kode_unit_audit' => '1903', 'nama_unit_audit' => 'INSPEKTORAT KAB. BANGKA SELATAN', 'jenis' => '0',],
            ['kode_unit_audit' => '1904', 'nama_unit_audit' => 'INSPEKTORAT KAB. BANGKA TENGAH', 'jenis' => '0',],
            ['kode_unit_audit' => '1905', 'nama_unit_audit' => 'INSPEKTORAT KAB. BANGKA BARAT', 'jenis' => '0',],
            ['kode_unit_audit' => '1906', 'nama_unit_audit' => 'INSPEKTORAT KAB. BELITUNG TIMUR', 'jenis' => '0',],
            ['kode_unit_audit' => '1971', 'nama_unit_audit' => 'INSPEKTORAT KOTA PANGKAL PINANG', 'jenis' => '0',],
            ['kode_unit_audit' => '2100', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI KEPULAUAN RIAU', 'jenis' => '1',],
            ['kode_unit_audit' => '2101', 'nama_unit_audit' => 'INSPEKTORAT KAB. BINTAN', 'jenis' => '0',],
            ['kode_unit_audit' => '2102', 'nama_unit_audit' => 'INSPEKTORAT KAB. KARIMUN', 'jenis' => '0',],
            ['kode_unit_audit' => '2103', 'nama_unit_audit' => 'INSPEKTORAT KAB. NATUNA', 'jenis' => '0',],
            ['kode_unit_audit' => '2104', 'nama_unit_audit' => 'INSPEKTORAT KAB. LINGGA', 'jenis' => '0',],
            ['kode_unit_audit' => '2105', 'nama_unit_audit' => 'INSPEKTORAT KAB. KEPULAUAN ANAMBAS', 'jenis' => '0',],
            ['kode_unit_audit' => '2171', 'nama_unit_audit' => 'INSPEKTORAT KOTA BATAM', 'jenis' => '0',],
            ['kode_unit_audit' => '2172', 'nama_unit_audit' => 'INSPEKTORAT KOTA TANJUNG PINANG', 'jenis' => '0',],
            ['kode_unit_audit' => '3100', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI DKI JAKARTA', 'jenis' => '1',],
            ['kode_unit_audit' => '3101', 'nama_unit_audit' => 'INSPEKTORAT KAB. ADM. KEP. SERIBU', 'jenis' => '0',],
            ['kode_unit_audit' => '3171', 'nama_unit_audit' => 'INSPEKTORAT KOTA ADM. JAKARTA PUSAT', 'jenis' => '0',],
            ['kode_unit_audit' => '3172', 'nama_unit_audit' => 'INSPEKTORAT KOTA ADM. JAKARTA UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '3173', 'nama_unit_audit' => 'INSPEKTORAT KOTA ADM. JAKARTA BARAT', 'jenis' => '0',],
            ['kode_unit_audit' => '3174', 'nama_unit_audit' => 'INSPEKTORAT KOTA ADM. JAKARTA SELATAN', 'jenis' => '0',],
            ['kode_unit_audit' => '3175', 'nama_unit_audit' => 'INSPEKTORAT KOTA ADM. JAKARTA TIMUR', 'jenis' => '0',],
            ['kode_unit_audit' => '3198', 'nama_unit_audit' => 'INSPEKTORAT SIMULASI (WORKSHOP)', 'jenis' => '1',],
            ['kode_unit_audit' => '3199', 'nama_unit_audit' => 'INSPEKTORAT LATIHAN (WORKSHOP)', 'jenis' => '1',],
            ['kode_unit_audit' => '3200', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI JAWA BARAT', 'jenis' => '1',],
            ['kode_unit_audit' => '3201', 'nama_unit_audit' => 'INSPEKTORAT KAB. BOGOR', 'jenis' => '0',],
            ['kode_unit_audit' => '3202', 'nama_unit_audit' => 'INSPEKTORAT KAB. SUKABUMI', 'jenis' => '0',],
            ['kode_unit_audit' => '3203', 'nama_unit_audit' => 'INSPEKTORAT KAB. CIANJUR', 'jenis' => '0',],
            ['kode_unit_audit' => '3204', 'nama_unit_audit' => 'INSPEKTORAT KAB. BANDUNG', 'jenis' => '0',],
            ['kode_unit_audit' => '3205', 'nama_unit_audit' => 'INSPEKTORAT KAB. GARUT', 'jenis' => '0',],
            ['kode_unit_audit' => '3206', 'nama_unit_audit' => 'INSPEKTORAT KAB. TASIKMALAYA', 'jenis' => '0',],
            ['kode_unit_audit' => '3207', 'nama_unit_audit' => 'INSPEKTORAT KAB. CIAMIS', 'jenis' => '0',],
            ['kode_unit_audit' => '3208', 'nama_unit_audit' => 'INSPEKTORAT KAB. KUNINGAN', 'jenis' => '0',],
            ['kode_unit_audit' => '3209', 'nama_unit_audit' => 'INSPEKTORAT KAB. CIREBON', 'jenis' => '0',],
            ['kode_unit_audit' => '3210', 'nama_unit_audit' => 'INSPEKTORAT KAB. MAJALENGKA', 'jenis' => '0',],
            ['kode_unit_audit' => '3211', 'nama_unit_audit' => 'INSPEKTORAT KAB. SUMEDANG', 'jenis' => '0',],
            ['kode_unit_audit' => '3212', 'nama_unit_audit' => 'INSPEKTORAT KAB. INDRAMAYU', 'jenis' => '0',],
            ['kode_unit_audit' => '3213', 'nama_unit_audit' => 'INSPEKTORAT KAB. SUBANG', 'jenis' => '0',],
            ['kode_unit_audit' => '3214', 'nama_unit_audit' => 'INSPEKTORAT KAB. PURWAKARTA', 'jenis' => '0',],
            ['kode_unit_audit' => '3215', 'nama_unit_audit' => 'INSPEKTORAT KAB. KARAWANG', 'jenis' => '0',],
            ['kode_unit_audit' => '3216', 'nama_unit_audit' => 'INSPEKTORAT KAB. BEKASI', 'jenis' => '0',],
            ['kode_unit_audit' => '3217', 'nama_unit_audit' => 'INSPEKTORAT KAB. BANDUNG BARAT', 'jenis' => '0',],
            ['kode_unit_audit' => '3218', 'nama_unit_audit' => 'INSPEKTORAT KAB. PANGANDARAN', 'jenis' => '0',],
            ['kode_unit_audit' => '3271', 'nama_unit_audit' => 'INSPEKTORAT KOTA BOGOR', 'jenis' => '0',],
            ['kode_unit_audit' => '3272', 'nama_unit_audit' => 'INSPEKTORAT KOTA SUKABUMI', 'jenis' => '0',],
            ['kode_unit_audit' => '3273', 'nama_unit_audit' => 'INSPEKTORAT KOTA BANDUNG', 'jenis' => '0',],
            ['kode_unit_audit' => '3274', 'nama_unit_audit' => 'INSPEKTORAT KOTA CIREBON', 'jenis' => '0',],
            ['kode_unit_audit' => '3275', 'nama_unit_audit' => 'INSPEKTORAT KOTA BEKASI', 'jenis' => '0',],
            ['kode_unit_audit' => '3276', 'nama_unit_audit' => 'INSPEKTORAT KOTA DEPOK', 'jenis' => '0',],
            ['kode_unit_audit' => '3277', 'nama_unit_audit' => 'INSPEKTORAT KOTA CIMAHI', 'jenis' => '0',],
            ['kode_unit_audit' => '3278', 'nama_unit_audit' => 'INSPEKTORAT KOTA TASIKMALAYA', 'jenis' => '0',],
            ['kode_unit_audit' => '3279', 'nama_unit_audit' => 'INSPEKTORAT KOTA BANJAR', 'jenis' => '0',],
            ['kode_unit_audit' => '3300', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI JAWA TENGAH', 'jenis' => '1',],
            ['kode_unit_audit' => '3301', 'nama_unit_audit' => 'INSPEKTORAT KAB. CILACAP', 'jenis' => '0',],
            ['kode_unit_audit' => '3302', 'nama_unit_audit' => 'INSPEKTORAT KAB. BANYUMAS', 'jenis' => '0',],
            ['kode_unit_audit' => '3303', 'nama_unit_audit' => 'INSPEKTORAT KAB. PURBALINGGA', 'jenis' => '0',],
            ['kode_unit_audit' => '3304', 'nama_unit_audit' => 'INSPEKTORAT KAB. BANJARNEGARA', 'jenis' => '0',],
            ['kode_unit_audit' => '3305', 'nama_unit_audit' => 'INSPEKTORAT KAB. KEBUMEN', 'jenis' => '0',],
            ['kode_unit_audit' => '3306', 'nama_unit_audit' => 'INSPEKTORAT KAB. PURWOREJO', 'jenis' => '0',],
            ['kode_unit_audit' => '3307', 'nama_unit_audit' => 'INSPEKTORAT KAB. WONOSOBO', 'jenis' => '0',],
            ['kode_unit_audit' => '3308', 'nama_unit_audit' => 'INSPEKTORAT KAB. MAGELANG', 'jenis' => '0',],
            ['kode_unit_audit' => '3309', 'nama_unit_audit' => 'INSPEKTORAT KAB. BOYOLALI', 'jenis' => '0',],
            ['kode_unit_audit' => '3310', 'nama_unit_audit' => 'INSPEKTORAT KAB. KLATEN', 'jenis' => '0',],
            ['kode_unit_audit' => '3311', 'nama_unit_audit' => 'INSPEKTORAT KAB. SUKOHARJO', 'jenis' => '0',],
            ['kode_unit_audit' => '3312', 'nama_unit_audit' => 'INSPEKTORAT KAB. WONOGIRI', 'jenis' => '0',],
            ['kode_unit_audit' => '3313', 'nama_unit_audit' => 'INSPEKTORAT KAB. KARANGANYAR', 'jenis' => '0',],
            ['kode_unit_audit' => '3314', 'nama_unit_audit' => 'INSPEKTORAT KAB. SRAGEN', 'jenis' => '0',],
            ['kode_unit_audit' => '3315', 'nama_unit_audit' => 'INSPEKTORAT KAB. GROBOGAN', 'jenis' => '0',],
            ['kode_unit_audit' => '3316', 'nama_unit_audit' => 'INSPEKTORAT KAB. BLORA', 'jenis' => '0',],
            ['kode_unit_audit' => '3317', 'nama_unit_audit' => 'INSPEKTORAT KAB. REMBANG', 'jenis' => '0',],
            ['kode_unit_audit' => '3318', 'nama_unit_audit' => 'INSPEKTORAT KAB. PATI', 'jenis' => '0',],
            ['kode_unit_audit' => '3319', 'nama_unit_audit' => 'INSPEKTORAT KAB. KUDUS', 'jenis' => '0',],
            ['kode_unit_audit' => '3320', 'nama_unit_audit' => 'INSPEKTORAT KAB. JEPARA', 'jenis' => '0',],
            ['kode_unit_audit' => '3321', 'nama_unit_audit' => 'INSPEKTORAT KAB. DEMAK', 'jenis' => '0',],
            ['kode_unit_audit' => '3322', 'nama_unit_audit' => 'INSPEKTORAT KAB. SEMARANG', 'jenis' => '0',],
            ['kode_unit_audit' => '3323', 'nama_unit_audit' => 'INSPEKTORAT KAB. TEMANGGUNG', 'jenis' => '0',],
            ['kode_unit_audit' => '3324', 'nama_unit_audit' => 'INSPEKTORAT KAB. KENDAL', 'jenis' => '0',],
            ['kode_unit_audit' => '3325', 'nama_unit_audit' => 'INSPEKTORAT KAB. BATANG', 'jenis' => '0',],
            ['kode_unit_audit' => '3326', 'nama_unit_audit' => 'INSPEKTORAT KAB. PEKALONGAN', 'jenis' => '0',],
            ['kode_unit_audit' => '3327', 'nama_unit_audit' => 'INSPEKTORAT KAB. PEMALANG', 'jenis' => '0',],
            ['kode_unit_audit' => '3328', 'nama_unit_audit' => 'INSPEKTORAT KAB. TEGAL', 'jenis' => '0',],
            ['kode_unit_audit' => '3329', 'nama_unit_audit' => 'INSPEKTORAT KAB. BREBES', 'jenis' => '0',],
            ['kode_unit_audit' => '3371', 'nama_unit_audit' => 'INSPEKTORAT KOTA MAGELANG', 'jenis' => '0',],
            ['kode_unit_audit' => '3372', 'nama_unit_audit' => 'INSPEKTORAT KOTA SURAKARTA', 'jenis' => '0',],
            ['kode_unit_audit' => '3373', 'nama_unit_audit' => 'INSPEKTORAT KOTA SALATIGA', 'jenis' => '0',],
            ['kode_unit_audit' => '3374', 'nama_unit_audit' => 'INSPEKTORAT KOTA SEMARANG', 'jenis' => '0',],
            ['kode_unit_audit' => '3375', 'nama_unit_audit' => 'INSPEKTORAT KOTA PEKALONGAN', 'jenis' => '0',],
            ['kode_unit_audit' => '3376', 'nama_unit_audit' => 'INSPEKTORAT KOTA TEGAL', 'jenis' => '0',],
            ['kode_unit_audit' => '3400', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI D.I. YOGYAKARTA', 'jenis' => '1',],
            ['kode_unit_audit' => '3401', 'nama_unit_audit' => 'INSPEKTORAT KAB. KULON PROGO', 'jenis' => '0',],
            ['kode_unit_audit' => '3402', 'nama_unit_audit' => 'INSPEKTORAT KAB. BANTUL', 'jenis' => '0',],
            ['kode_unit_audit' => '3403', 'nama_unit_audit' => 'INSPEKTORAT KAB. GUNUNGKIDUL', 'jenis' => '0',],
            ['kode_unit_audit' => '3404', 'nama_unit_audit' => 'INSPEKTORAT KAB. SLEMAN', 'jenis' => '0',],
            ['kode_unit_audit' => '3471', 'nama_unit_audit' => 'INSPEKTORAT KOTA YOGYAKARTA', 'jenis' => '0',],
            ['kode_unit_audit' => '3500', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI JAWA TIMUR', 'jenis' => '1',],
            ['kode_unit_audit' => '3501', 'nama_unit_audit' => 'INSPEKTORAT KAB. PACITAN', 'jenis' => '0',],
            ['kode_unit_audit' => '3502', 'nama_unit_audit' => 'INSPEKTORAT KAB. PONOROGO', 'jenis' => '0',],
            ['kode_unit_audit' => '3503', 'nama_unit_audit' => 'INSPEKTORAT KAB. TRENGGALEK', 'jenis' => '0',],
            ['kode_unit_audit' => '3504', 'nama_unit_audit' => 'INSPEKTORAT KAB. TULUNGAGUNG', 'jenis' => '0',],
            ['kode_unit_audit' => '3505', 'nama_unit_audit' => 'INSPEKTORAT KAB. BLITAR', 'jenis' => '0',],
            ['kode_unit_audit' => '3506', 'nama_unit_audit' => 'INSPEKTORAT KAB. KEDIRI', 'jenis' => '0',],
            ['kode_unit_audit' => '3507', 'nama_unit_audit' => 'INSPEKTORAT KAB. MALANG', 'jenis' => '0',],
            ['kode_unit_audit' => '3508', 'nama_unit_audit' => 'INSPEKTORAT KAB. LUMAJANG', 'jenis' => '0',],
            ['kode_unit_audit' => '3509', 'nama_unit_audit' => 'INSPEKTORAT KAB. JEMBER', 'jenis' => '0',],
            ['kode_unit_audit' => '3510', 'nama_unit_audit' => 'INSPEKTORAT KAB. BANYUWANGI', 'jenis' => '0',],
            ['kode_unit_audit' => '3511', 'nama_unit_audit' => 'INSPEKTORAT KAB. BONDOWOSO', 'jenis' => '0',],
            ['kode_unit_audit' => '3512', 'nama_unit_audit' => 'INSPEKTORAT KAB. SITUBONDO', 'jenis' => '0',],
            ['kode_unit_audit' => '3513', 'nama_unit_audit' => 'INSPEKTORAT KAB. PROBOLINGGO', 'jenis' => '0',],
            ['kode_unit_audit' => '3514', 'nama_unit_audit' => 'INSPEKTORAT KAB. PASURUAN', 'jenis' => '0',],
            ['kode_unit_audit' => '3515', 'nama_unit_audit' => 'INSPEKTORAT KAB. SIDOARJO', 'jenis' => '0',],
            ['kode_unit_audit' => '3516', 'nama_unit_audit' => 'INSPEKTORAT KAB. MOJOKERTO', 'jenis' => '0',],
            ['kode_unit_audit' => '3517', 'nama_unit_audit' => 'INSPEKTORAT KAB. JOMBANG', 'jenis' => '0',],
            ['kode_unit_audit' => '3518', 'nama_unit_audit' => 'INSPEKTORAT KAB. NGANJUK', 'jenis' => '0',],
            ['kode_unit_audit' => '3519', 'nama_unit_audit' => 'INSPEKTORAT KAB. MADIUN', 'jenis' => '0',],
            ['kode_unit_audit' => '3520', 'nama_unit_audit' => 'INSPEKTORAT KAB. MAGETAN', 'jenis' => '0',],
            ['kode_unit_audit' => '3521', 'nama_unit_audit' => 'INSPEKTORAT KAB. NGAWI', 'jenis' => '0',],
            ['kode_unit_audit' => '3522', 'nama_unit_audit' => 'INSPEKTORAT KAB. BOJONEGORO', 'jenis' => '0',],
            ['kode_unit_audit' => '3523', 'nama_unit_audit' => 'INSPEKTORAT KAB. TUBAN', 'jenis' => '0',],
            ['kode_unit_audit' => '3524', 'nama_unit_audit' => 'INSPEKTORAT KAB. LAMONGAN', 'jenis' => '0',],
            ['kode_unit_audit' => '3525', 'nama_unit_audit' => 'INSPEKTORAT KAB. GRESIK', 'jenis' => '0',],
            ['kode_unit_audit' => '3526', 'nama_unit_audit' => 'INSPEKTORAT KAB. BANGKALAN', 'jenis' => '0',],
            ['kode_unit_audit' => '3527', 'nama_unit_audit' => 'INSPEKTORAT KAB. SAMPANG', 'jenis' => '0',],
            ['kode_unit_audit' => '3528', 'nama_unit_audit' => 'INSPEKTORAT KAB. PAMEKASAN', 'jenis' => '0',],
            ['kode_unit_audit' => '3529', 'nama_unit_audit' => 'INSPEKTORAT KAB. SUMENEP', 'jenis' => '0',],
            ['kode_unit_audit' => '3571', 'nama_unit_audit' => 'INSPEKTORAT KOTA KEDIRI', 'jenis' => '0',],
            ['kode_unit_audit' => '3572', 'nama_unit_audit' => 'INSPEKTORAT KOTA BLITAR', 'jenis' => '0',],
            ['kode_unit_audit' => '3573', 'nama_unit_audit' => 'INSPEKTORAT KOTA MALANG', 'jenis' => '0',],
            ['kode_unit_audit' => '3574', 'nama_unit_audit' => 'INSPEKTORAT KOTA PROBOLINGGO', 'jenis' => '0',],
            ['kode_unit_audit' => '3575', 'nama_unit_audit' => 'INSPEKTORAT KOTA PASURUAN', 'jenis' => '0',],
            ['kode_unit_audit' => '3576', 'nama_unit_audit' => 'INSPEKTORAT KOTA MOJOKERTO', 'jenis' => '0',],
            ['kode_unit_audit' => '3577', 'nama_unit_audit' => 'INSPEKTORAT KOTA MADIUN', 'jenis' => '0',],
            ['kode_unit_audit' => '3578', 'nama_unit_audit' => 'INSPEKTORAT KOTA SURABAYA', 'jenis' => '0',],
            ['kode_unit_audit' => '3579', 'nama_unit_audit' => 'INSPEKTORAT KOTA BATU', 'jenis' => '0',],
            ['kode_unit_audit' => '3600', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI BANTEN', 'jenis' => '1',],
            ['kode_unit_audit' => '3601', 'nama_unit_audit' => 'INSPEKTORAT KAB. PANDEGLANG', 'jenis' => '0',],
            ['kode_unit_audit' => '3602', 'nama_unit_audit' => 'INSPEKTORAT KAB. LEBAK', 'jenis' => '0',],
            ['kode_unit_audit' => '3603', 'nama_unit_audit' => 'INSPEKTORAT KAB. TANGERANG', 'jenis' => '0',],
            ['kode_unit_audit' => '3604', 'nama_unit_audit' => 'INSPEKTORAT KAB. SERANG', 'jenis' => '0',],
            ['kode_unit_audit' => '3671', 'nama_unit_audit' => 'INSPEKTORAT KOTA TANGERANG', 'jenis' => '0',],
            ['kode_unit_audit' => '5100', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI BALI', 'jenis' => '1',],
            ['kode_unit_audit' => '5101', 'nama_unit_audit' => 'INSPEKTORAT KAB. JEMBRANA', 'jenis' => '0',],
            ['kode_unit_audit' => '5102', 'nama_unit_audit' => 'INSPEKTORAT KAB. TABANAN', 'jenis' => '0',],
            ['kode_unit_audit' => '5103', 'nama_unit_audit' => 'INSPEKTORAT KAB. BADUNG', 'jenis' => '0',],
            ['kode_unit_audit' => '5104', 'nama_unit_audit' => 'INSPEKTORAT KAB. GIANYAR', 'jenis' => '0',],
            ['kode_unit_audit' => '5105', 'nama_unit_audit' => 'INSPEKTORAT KAB. KLUNGKUNG', 'jenis' => '0',],
            ['kode_unit_audit' => '5106', 'nama_unit_audit' => 'INSPEKTORAT KAB. BANGLI', 'jenis' => '0',],
            ['kode_unit_audit' => '5107', 'nama_unit_audit' => 'INSPEKTORAT KAB. KARANGASEM', 'jenis' => '0',],
            ['kode_unit_audit' => '5108', 'nama_unit_audit' => 'INSPEKTORAT KAB. BULELENG', 'jenis' => '0',],
            ['kode_unit_audit' => '5171', 'nama_unit_audit' => 'INSPEKTORAT KOTA DENPASAR', 'jenis' => '0',],
            ['kode_unit_audit' => '5200', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI NUSA TENGGARA BARAT', 'jenis' => '1',],
            ['kode_unit_audit' => '5201', 'nama_unit_audit' => 'INSPEKTORAT KAB. LOMBOK BARAT', 'jenis' => '0',],
            ['kode_unit_audit' => '5202', 'nama_unit_audit' => 'INSPEKTORAT KAB. LOMBOK TENGAH', 'jenis' => '0',],
            ['kode_unit_audit' => '5203', 'nama_unit_audit' => 'INSPEKTORAT KAB. LOMBOK TIMUR', 'jenis' => '0',],
            ['kode_unit_audit' => '5204', 'nama_unit_audit' => 'INSPEKTORAT KAB. SUMBAWA', 'jenis' => '0',],
            ['kode_unit_audit' => '5205', 'nama_unit_audit' => 'INSPEKTORAT KAB. DOMPU', 'jenis' => '0',],
            ['kode_unit_audit' => '5206', 'nama_unit_audit' => 'INSPEKTORAT KAB. BIMA', 'jenis' => '0',],
            ['kode_unit_audit' => '5207', 'nama_unit_audit' => 'INSPEKTORAT KAB. SUMBAWA BARAT', 'jenis' => '0',],
            ['kode_unit_audit' => '5271', 'nama_unit_audit' => 'INSPEKTORAT KOTA MATARAM', 'jenis' => '0',],
            ['kode_unit_audit' => '5272', 'nama_unit_audit' => 'INSPEKTORAT KOTA BIMA', 'jenis' => '0',],
            ['kode_unit_audit' => '5300', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI NUSA TENGGARA TIMUR', 'jenis' => '1',],
            ['kode_unit_audit' => '5301', 'nama_unit_audit' => 'INSPEKTORAT KAB. KUPANG', 'jenis' => '0',],
            ['kode_unit_audit' => '5302', 'nama_unit_audit' => 'INSPEKTORAT KAB. TIMOR TENGAH SELATAN', 'jenis' => '0',],
            ['kode_unit_audit' => '5303', 'nama_unit_audit' => 'INSPEKTORAT KAB. TIMOR TENGAH UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '5304', 'nama_unit_audit' => 'INSPEKTORAT KAB. BELU', 'jenis' => '0',],
            ['kode_unit_audit' => '5305', 'nama_unit_audit' => 'INSPEKTORAT KAB. ALOR', 'jenis' => '0',],
            ['kode_unit_audit' => '5306', 'nama_unit_audit' => 'INSPEKTORAT KAB. FLORES TIMUR', 'jenis' => '0',],
            ['kode_unit_audit' => '5307', 'nama_unit_audit' => 'INSPEKTORAT KAB. SIKKA', 'jenis' => '0',],
            ['kode_unit_audit' => '5308', 'nama_unit_audit' => 'INSPEKTORAT KAB. ENDE', 'jenis' => '0',],
            ['kode_unit_audit' => '5309', 'nama_unit_audit' => 'INSPEKTORAT KAB. NGADA', 'jenis' => '0',],
            ['kode_unit_audit' => '5310', 'nama_unit_audit' => 'INSPEKTORAT KAB. MANGGARAI', 'jenis' => '0',],
            ['kode_unit_audit' => '5311', 'nama_unit_audit' => 'INSPEKTORAT KAB. SUMBA TIMUR', 'jenis' => '0',],
            ['kode_unit_audit' => '5312', 'nama_unit_audit' => 'INSPEKTORAT KAB. SUMBA BARAT', 'jenis' => '0',],
            ['kode_unit_audit' => '5313', 'nama_unit_audit' => 'INSPEKTORAT KAB. LEMBATA', 'jenis' => '0',],
            ['kode_unit_audit' => '5314', 'nama_unit_audit' => 'INSPEKTORAT KAB. ROTE NDAO', 'jenis' => '0',],
            ['kode_unit_audit' => '5315', 'nama_unit_audit' => 'INSPEKTORAT KAB. MANGGARAI BARAT', 'jenis' => '0',],
            ['kode_unit_audit' => '5316', 'nama_unit_audit' => 'INSPEKTORAT KAB. NAGEKEO', 'jenis' => '0',],
            ['kode_unit_audit' => '5317', 'nama_unit_audit' => 'INSPEKTORAT KAB. SUMBA TENGAH', 'jenis' => '0',],
            ['kode_unit_audit' => '5318', 'nama_unit_audit' => 'INSPEKTORAT KAB. SUMBA BARAT DAYA', 'jenis' => '0',],
            ['kode_unit_audit' => '5319', 'nama_unit_audit' => 'INSPEKTORAT KAB. MANGGARAI TIMUR', 'jenis' => '0',],
            ['kode_unit_audit' => '5320', 'nama_unit_audit' => 'INSPEKTORAT KAB. SABU RAIJUA', 'jenis' => '0',],
            ['kode_unit_audit' => '5321', 'nama_unit_audit' => 'INSPEKTORAT KAB. MALAKA', 'jenis' => '0',],
            ['kode_unit_audit' => '5371', 'nama_unit_audit' => 'INSPEKTORAT KOTA KUPANG', 'jenis' => '0',],
            ['kode_unit_audit' => '6100', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI KALIMANTAN BARAT', 'jenis' => '1',],
            ['kode_unit_audit' => '6101', 'nama_unit_audit' => 'INSPEKTORAT KAB. SAMBAS', 'jenis' => '0',],
            ['kode_unit_audit' => '6102', 'nama_unit_audit' => 'INSPEKTORAT KAB. MEMPAWAH', 'jenis' => '0',],
            ['kode_unit_audit' => '6103', 'nama_unit_audit' => 'INSPEKTORAT KAB. SANGGAU', 'jenis' => '0',],
            ['kode_unit_audit' => '6104', 'nama_unit_audit' => 'INSPEKTORAT KAB. KETAPANG', 'jenis' => '0',],
            ['kode_unit_audit' => '6105', 'nama_unit_audit' => 'INSPEKTORAT KAB. SINTANG', 'jenis' => '0',],
            ['kode_unit_audit' => '6106', 'nama_unit_audit' => 'INSPEKTORAT KAB. KAPUAS HULU', 'jenis' => '0',],
            ['kode_unit_audit' => '6107', 'nama_unit_audit' => 'INSPEKTORAT KAB. BENGKAYANG', 'jenis' => '0',],
            ['kode_unit_audit' => '6108', 'nama_unit_audit' => 'INSPEKTORAT KAB. LANDAK', 'jenis' => '0',],
            ['kode_unit_audit' => '6109', 'nama_unit_audit' => 'INSPEKTORAT KAB. SEKADAU', 'jenis' => '0',],
            ['kode_unit_audit' => '6110', 'nama_unit_audit' => 'INSPEKTORAT KAB. MELAWI', 'jenis' => '0',],
            ['kode_unit_audit' => '6111', 'nama_unit_audit' => 'INSPEKTORAT KAB. KAYONG UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '6112', 'nama_unit_audit' => 'INSPEKTORAT KAB. KUBU RAYA', 'jenis' => '0',],
            ['kode_unit_audit' => '6171', 'nama_unit_audit' => 'INSPEKTORAT KOTA PONTIANAK', 'jenis' => '0',],
            ['kode_unit_audit' => '6172', 'nama_unit_audit' => 'INSPEKTORAT KOTA SINGKAWANG', 'jenis' => '0',],
            ['kode_unit_audit' => '6200', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI KALIMANTAN TENGAH', 'jenis' => '1',],
            ['kode_unit_audit' => '6201', 'nama_unit_audit' => 'INSPEKTORAT KAB. KOTAWARINGIN BARAT', 'jenis' => '0',],
            ['kode_unit_audit' => '6202', 'nama_unit_audit' => 'INSPEKTORAT KAB. KOTAWARINGIN TIMUR', 'jenis' => '0',],
            ['kode_unit_audit' => '6203', 'nama_unit_audit' => 'INSPEKTORAT KAB. KAPUAS', 'jenis' => '0',],
            ['kode_unit_audit' => '6204', 'nama_unit_audit' => 'INSPEKTORAT KAB. BARITO SELATAN', 'jenis' => '0',],
            ['kode_unit_audit' => '6205', 'nama_unit_audit' => 'INSPEKTORAT KAB. BARITO UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '6206', 'nama_unit_audit' => 'INSPEKTORAT KAB. KATINGAN', 'jenis' => '0',],
            ['kode_unit_audit' => '6207', 'nama_unit_audit' => 'INSPEKTORAT KAB. SERUYAN', 'jenis' => '0',],
            ['kode_unit_audit' => '6208', 'nama_unit_audit' => 'INSPEKTORAT KAB. SUKAMARA', 'jenis' => '0',],
            ['kode_unit_audit' => '6209', 'nama_unit_audit' => 'INSPEKTORAT KAB. LAMANDAU', 'jenis' => '0',],
            ['kode_unit_audit' => '6210', 'nama_unit_audit' => 'INSPEKTORAT KAB. GUNUNG MAS', 'jenis' => '0',],
            ['kode_unit_audit' => '6211', 'nama_unit_audit' => 'INSPEKTORAT KAB. PULANG PISAU', 'jenis' => '0',],
            ['kode_unit_audit' => '6212', 'nama_unit_audit' => 'INSPEKTORAT KAB. MURUNG RAYA', 'jenis' => '0',],
            ['kode_unit_audit' => '6213', 'nama_unit_audit' => 'INSPEKTORAT KAB. BARITO TIMUR', 'jenis' => '0',],
            ['kode_unit_audit' => '6271', 'nama_unit_audit' => 'INSPEKTORAT KOTA PALANGKARAYA', 'jenis' => '0',],
            ['kode_unit_audit' => '6300', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI KALIMANTAN SELATAN', 'jenis' => '1',],
            ['kode_unit_audit' => '6301', 'nama_unit_audit' => 'INSPEKTORAT KAB. TANAH LAUT', 'jenis' => '0',],
            ['kode_unit_audit' => '6302', 'nama_unit_audit' => 'INSPEKTORAT KAB. KOTABARU', 'jenis' => '0',],
            ['kode_unit_audit' => '6303', 'nama_unit_audit' => 'INSPEKTORAT KAB. BANJAR', 'jenis' => '0',],
            ['kode_unit_audit' => '6304', 'nama_unit_audit' => 'INSPEKTORAT KAB. BARITO KUALA', 'jenis' => '0',],
            ['kode_unit_audit' => '6305', 'nama_unit_audit' => 'INSPEKTORAT KAB. TAPIN', 'jenis' => '0',],
            ['kode_unit_audit' => '6306', 'nama_unit_audit' => 'INSPEKTORAT KAB. HULU SUNGAI SELATAN', 'jenis' => '0',],
            ['kode_unit_audit' => '6307', 'nama_unit_audit' => 'INSPEKTORAT KAB. HULU SUNGAI TENGAH', 'jenis' => '0',],
            ['kode_unit_audit' => '6308', 'nama_unit_audit' => 'INSPEKTORAT KAB. HULU SUNGAI UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '6309', 'nama_unit_audit' => 'INSPEKTORAT KAB. TABALONG', 'jenis' => '0',],
            ['kode_unit_audit' => '6310', 'nama_unit_audit' => 'INSPEKTORAT KAB. TANAH BUMBU', 'jenis' => '0',],
            ['kode_unit_audit' => '6311', 'nama_unit_audit' => 'INSPEKTORAT KAB. BALANGAN', 'jenis' => '0',],
            ['kode_unit_audit' => '6371', 'nama_unit_audit' => 'INSPEKTORAT KOTA BANJARMASIN', 'jenis' => '0',],
            ['kode_unit_audit' => '6372', 'nama_unit_audit' => 'INSPEKTORAT KOTA BANJARBARU', 'jenis' => '0',],
            ['kode_unit_audit' => '6400', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI KALIMANTAN TIMUR', 'jenis' => '1',],
            ['kode_unit_audit' => '6401', 'nama_unit_audit' => 'INSPEKTORAT KAB. PASER', 'jenis' => '0',],
            ['kode_unit_audit' => '6402', 'nama_unit_audit' => 'INSPEKTORAT KAB. KUTAI KARTANEGARA', 'jenis' => '0',],
            ['kode_unit_audit' => '6403', 'nama_unit_audit' => 'INSPEKTORAT KAB. BERAU', 'jenis' => '0',],
            ['kode_unit_audit' => '6407', 'nama_unit_audit' => 'INSPEKTORAT KAB. KUTAI BARAT', 'jenis' => '0',],
            ['kode_unit_audit' => '6408', 'nama_unit_audit' => 'INSPEKTORAT KAB. KUTAI TIMUR', 'jenis' => '0',],
            ['kode_unit_audit' => '6409', 'nama_unit_audit' => 'INSPEKTORAT KAB. PENAJAM PASER UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '6411', 'nama_unit_audit' => 'INSPEKTORAT KAB. MAHAKAM ULU', 'jenis' => '0',],
            ['kode_unit_audit' => '6471', 'nama_unit_audit' => 'INSPEKTORAT KOTA BALIKPAPAN', 'jenis' => '0',],
            ['kode_unit_audit' => '6472', 'nama_unit_audit' => 'INSPEKTORAT KOTA SAMARINDA', 'jenis' => '0',],
            ['kode_unit_audit' => '6474', 'nama_unit_audit' => 'INSPEKTORAT KOTA BONTANG', 'jenis' => '0',],
            ['kode_unit_audit' => '6500', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI KALIMANTAN UTARA', 'jenis' => '1',],
            ['kode_unit_audit' => '6501', 'nama_unit_audit' => 'INSPEKTORAT KAB. BULUNGAN', 'jenis' => '0',],
            ['kode_unit_audit' => '6502', 'nama_unit_audit' => 'INSPEKTORAT KAB. MALINAU', 'jenis' => '0',],
            ['kode_unit_audit' => '6503', 'nama_unit_audit' => 'INSPEKTORAT KAB. NUNUKAN', 'jenis' => '0',],
            ['kode_unit_audit' => '6504', 'nama_unit_audit' => 'INSPEKTORAT KAB. TANA TIDUNG', 'jenis' => '0',],
            ['kode_unit_audit' => '6571', 'nama_unit_audit' => 'INSPEKTORAT KOTA TARAKAN', 'jenis' => '0',],
            ['kode_unit_audit' => '7100', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI SULAWESI UTARA', 'jenis' => '1',],
            ['kode_unit_audit' => '7101', 'nama_unit_audit' => 'INSPEKTORAT KAB. BOLAANG MONGONDOW', 'jenis' => '0',],
            ['kode_unit_audit' => '7102', 'nama_unit_audit' => 'INSPEKTORAT KAB. MINAHASA', 'jenis' => '0',],
            ['kode_unit_audit' => '7103', 'nama_unit_audit' => 'INSPEKTORAT KAB. KEPULAUAN SANGIHE', 'jenis' => '0',],
            ['kode_unit_audit' => '7104', 'nama_unit_audit' => 'INSPEKTORAT KAB. KEPULAUAN TALAUD', 'jenis' => '0',],
            ['kode_unit_audit' => '7105', 'nama_unit_audit' => 'INSPEKTORAT KAB. MINAHASA SELATAN', 'jenis' => '0',],
            ['kode_unit_audit' => '7106', 'nama_unit_audit' => 'INSPEKTORAT KAB. MINAHASA UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '7107', 'nama_unit_audit' => 'INSPEKTORAT KAB. MINAHASA TENGGARA', 'jenis' => '0',],
            ['kode_unit_audit' => '7108', 'nama_unit_audit' => 'INSPEKTORAT KAB. BOLAANG MONGONDOW UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '7109', 'nama_unit_audit' => 'INSPEKTORAT KAB. KEP. SIAU TAGULANDANG BIARO', 'jenis' => '0',],
            ['kode_unit_audit' => '7110', 'nama_unit_audit' => 'INSPEKTORAT KAB. BOLAANG MONGONDOW TIMUR', 'jenis' => '0',],
            ['kode_unit_audit' => '7111', 'nama_unit_audit' => 'INSPEKTORAT KAB. BOLAANG MONGONDOW SELATAN', 'jenis' => '0',],
            ['kode_unit_audit' => '7171', 'nama_unit_audit' => 'INSPEKTORAT KOTA MANADO', 'jenis' => '0',],
            ['kode_unit_audit' => '7172', 'nama_unit_audit' => 'INSPEKTORAT KOTA BITUNG', 'jenis' => '0',],
            ['kode_unit_audit' => '7200', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI SULAWESI TENGAH', 'jenis' => '1',],
            ['kode_unit_audit' => '7201', 'nama_unit_audit' => 'INSPEKTORAT KAB. BANGGAI', 'jenis' => '0',],
            ['kode_unit_audit' => '7202', 'nama_unit_audit' => 'INSPEKTORAT KAB. POSO', 'jenis' => '0',],
            ['kode_unit_audit' => '7203', 'nama_unit_audit' => 'INSPEKTORAT KAB. DONGGALA', 'jenis' => '0',],
            ['kode_unit_audit' => '7204', 'nama_unit_audit' => 'INSPEKTORAT KAB. TOLI TOLI', 'jenis' => '0',],
            ['kode_unit_audit' => '7205', 'nama_unit_audit' => 'INSPEKTORAT KAB. BUOL', 'jenis' => '0',],
            ['kode_unit_audit' => '7206', 'nama_unit_audit' => 'INSPEKTORAT KAB. MOROWALI', 'jenis' => '0',],
            ['kode_unit_audit' => '7207', 'nama_unit_audit' => 'INSPEKTORAT KAB. BANGGAI KEPULAUAN', 'jenis' => '0',],
            ['kode_unit_audit' => '7208', 'nama_unit_audit' => 'INSPEKTORAT KAB. PARIGI MOUTONG', 'jenis' => '0',],
            ['kode_unit_audit' => '7209', 'nama_unit_audit' => 'INSPEKTORAT KAB. TOJO UNA UNA', 'jenis' => '0',],
            ['kode_unit_audit' => '7210', 'nama_unit_audit' => 'INSPEKTORAT KAB. SIGI', 'jenis' => '0',],
            ['kode_unit_audit' => '7211', 'nama_unit_audit' => 'INSPEKTORAT KAB. BANGGAI LAUT', 'jenis' => '0',],
            ['kode_unit_audit' => '7212', 'nama_unit_audit' => 'INSPEKTORAT KAB. MOROWALI UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '7271', 'nama_unit_audit' => 'INSPEKTORAT KOTA PALU', 'jenis' => '0',],
            ['kode_unit_audit' => '7300', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI SULAWESI SELATAN', 'jenis' => '1',],
            ['kode_unit_audit' => '7301', 'nama_unit_audit' => 'INSPEKTORAT KAB. KEPULAUAN SELAYAR', 'jenis' => '0',],
            ['kode_unit_audit' => '7302', 'nama_unit_audit' => 'INSPEKTORAT KAB. BULUKUMBA', 'jenis' => '0',],
            ['kode_unit_audit' => '7303', 'nama_unit_audit' => 'INSPEKTORAT KAB. BANTAENG', 'jenis' => '0',],
            ['kode_unit_audit' => '7304', 'nama_unit_audit' => 'INSPEKTORAT KAB. JENEPONTO', 'jenis' => '0',],
            ['kode_unit_audit' => '7305', 'nama_unit_audit' => 'INSPEKTORAT KAB. TAKALAR', 'jenis' => '0',],
            ['kode_unit_audit' => '7306', 'nama_unit_audit' => 'INSPEKTORAT KAB. GOWA', 'jenis' => '0',],
            ['kode_unit_audit' => '7307', 'nama_unit_audit' => 'INSPEKTORAT KAB. SINJAI', 'jenis' => '0',],
            ['kode_unit_audit' => '7308', 'nama_unit_audit' => 'INSPEKTORAT KAB. BONE', 'jenis' => '0',],
            ['kode_unit_audit' => '7309', 'nama_unit_audit' => 'INSPEKTORAT KAB. MAROS', 'jenis' => '0',],
            ['kode_unit_audit' => '7310', 'nama_unit_audit' => 'INSPEKTORAT KAB. PANGKAJENE KEPULAUAN', 'jenis' => '0',],
            ['kode_unit_audit' => '7311', 'nama_unit_audit' => 'INSPEKTORAT KAB. BARRU', 'jenis' => '0',],
            ['kode_unit_audit' => '7312', 'nama_unit_audit' => 'INSPEKTORAT KAB. SOPPENG', 'jenis' => '0',],
            ['kode_unit_audit' => '7313', 'nama_unit_audit' => 'INSPEKTORAT KAB. WAJO', 'jenis' => '0',],
            ['kode_unit_audit' => '7314', 'nama_unit_audit' => 'INSPEKTORAT KAB. SIDENRENG RAPPANG', 'jenis' => '0',],
            ['kode_unit_audit' => '7315', 'nama_unit_audit' => 'INSPEKTORAT KAB. PINRANG', 'jenis' => '0',],
            ['kode_unit_audit' => '7316', 'nama_unit_audit' => 'INSPEKTORAT KAB. ENREKANG', 'jenis' => '0',],
            ['kode_unit_audit' => '7317', 'nama_unit_audit' => 'INSPEKTORAT KAB. LUWU', 'jenis' => '0',],
            ['kode_unit_audit' => '7318', 'nama_unit_audit' => 'INSPEKTORAT KAB. TANA TORAJA', 'jenis' => '0',],
            ['kode_unit_audit' => '7322', 'nama_unit_audit' => 'INSPEKTORAT KAB. LUWU UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '7324', 'nama_unit_audit' => 'INSPEKTORAT KAB. LUWU TIMUR', 'jenis' => '0',],
            ['kode_unit_audit' => '7326', 'nama_unit_audit' => 'INSPEKTORAT KAB. TORAJA UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '7371', 'nama_unit_audit' => 'INSPEKTORAT KOTA MAKASSAR', 'jenis' => '0',],
            ['kode_unit_audit' => '7372', 'nama_unit_audit' => 'INSPEKTORAT KOTA PARE PARE', 'jenis' => '0',],
            ['kode_unit_audit' => '7373', 'nama_unit_audit' => 'INSPEKTORAT KOTA PALOPO', 'jenis' => '0',],
            ['kode_unit_audit' => '7400', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI SULAWESI TENGGARA', 'jenis' => '1',],
            ['kode_unit_audit' => '7401', 'nama_unit_audit' => 'INSPEKTORAT KAB. KOLAKA', 'jenis' => '0',],
            ['kode_unit_audit' => '7402', 'nama_unit_audit' => 'INSPEKTORAT KAB. KONAWE', 'jenis' => '0',],
            ['kode_unit_audit' => '7403', 'nama_unit_audit' => 'INSPEKTORAT KAB. MUNA', 'jenis' => '0',],
            ['kode_unit_audit' => '7404', 'nama_unit_audit' => 'INSPEKTORAT KAB. BUTON', 'jenis' => '0',],
            ['kode_unit_audit' => '7405', 'nama_unit_audit' => 'INSPEKTORAT KAB. KONAWE SELATAN', 'jenis' => '0',],
            ['kode_unit_audit' => '7406', 'nama_unit_audit' => 'INSPEKTORAT KAB. BOMBANA', 'jenis' => '0',],
            ['kode_unit_audit' => '7407', 'nama_unit_audit' => 'INSPEKTORAT KAB. WAKATOBI', 'jenis' => '0',],
            ['kode_unit_audit' => '7408', 'nama_unit_audit' => 'INSPEKTORAT KAB. KOLAKA UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '7409', 'nama_unit_audit' => 'INSPEKTORAT KAB. KONAWE UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '7410', 'nama_unit_audit' => 'INSPEKTORAT KAB. BUTON UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '7411', 'nama_unit_audit' => 'INSPEKTORAT KAB. KOLAKA TIMUR', 'jenis' => '0',],
            ['kode_unit_audit' => '7412', 'nama_unit_audit' => 'INSPEKTORAT KAB. KONAWE KEPULAUAN', 'jenis' => '0',],
            ['kode_unit_audit' => '7413', 'nama_unit_audit' => 'INSPEKTORAT KAB. MUNA BARAT', 'jenis' => '0',],
            ['kode_unit_audit' => '7414', 'nama_unit_audit' => 'INSPEKTORAT KAB. BUTON TENGAH', 'jenis' => '0',],
            ['kode_unit_audit' => '7415', 'nama_unit_audit' => 'INSPEKTORAT KAB. BUTON SELATAN', 'jenis' => '0',],
            ['kode_unit_audit' => '7471', 'nama_unit_audit' => 'INSPEKTORAT KOTA KENDARI', 'jenis' => '0',],
            ['kode_unit_audit' => '7472', 'nama_unit_audit' => 'INSPEKTORAT KOTA BAU BAU', 'jenis' => '0',],
            ['kode_unit_audit' => '7499', 'nama_unit_audit' => 'INSPEKTORAT SIMULASI SULAWESI TENGGARA (WORKSHOP)', 'jenis' => '1',],
            ['kode_unit_audit' => '7500', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI GORONTALO', 'jenis' => '1',],
            ['kode_unit_audit' => '7501', 'nama_unit_audit' => 'INSPEKTORAT KAB. GORONTALO', 'jenis' => '0',],
            ['kode_unit_audit' => '7502', 'nama_unit_audit' => 'INSPEKTORAT KAB. BOALEMO', 'jenis' => '0',],
            ['kode_unit_audit' => '7503', 'nama_unit_audit' => 'INSPEKTORAT KAB. BONE BOLANGO', 'jenis' => '0',],
            ['kode_unit_audit' => '7504', 'nama_unit_audit' => 'INSPEKTORAT KAB. PAHUWATO', 'jenis' => '0',],
            ['kode_unit_audit' => '7505', 'nama_unit_audit' => 'INSPEKTORAT KAB. GORONTALO UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '7571', 'nama_unit_audit' => 'INSPEKTORAT KOTA GORONTALO', 'jenis' => '0',],
            ['kode_unit_audit' => '7600', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI SULAWESI BARAT', 'jenis' => '1',],
            ['kode_unit_audit' => '7601', 'nama_unit_audit' => 'INSPEKTORAT KAB. MAMUJU UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '7602', 'nama_unit_audit' => 'INSPEKTORAT KAB. MAMUJU', 'jenis' => '0',],
            ['kode_unit_audit' => '7603', 'nama_unit_audit' => 'INSPEKTORAT KAB. MAMASA', 'jenis' => '0',],
            ['kode_unit_audit' => '7604', 'nama_unit_audit' => 'INSPEKTORAT KAB. POLEWALI MANDAR', 'jenis' => '0',],
            ['kode_unit_audit' => '7605', 'nama_unit_audit' => 'INSPEKTORAT KAB. MAJENE', 'jenis' => '0',],
            ['kode_unit_audit' => '7606', 'nama_unit_audit' => 'INSPEKTORAT KAB. MAMUJU TENGAH', 'jenis' => '0',],
            ['kode_unit_audit' => '8100', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI MALUKU', 'jenis' => '1',],
            ['kode_unit_audit' => '8101', 'nama_unit_audit' => 'INSPEKTORAT KAB. MALUKU TENGAH', 'jenis' => '0',],
            ['kode_unit_audit' => '8102', 'nama_unit_audit' => 'INSPEKTORAT KAB. MALUKU TENGGARA', 'jenis' => '0',],
            ['kode_unit_audit' => '8103', 'nama_unit_audit' => 'INSPEKTORAT KAB. MALUKU TENGGARA BARAT', 'jenis' => '0',],
            ['kode_unit_audit' => '8104', 'nama_unit_audit' => 'INSPEKTORAT KAB. BURU', 'jenis' => '0',],
            ['kode_unit_audit' => '8105', 'nama_unit_audit' => 'INSPEKTORAT KAB. SERAM BAGIAN TIMUR', 'jenis' => '0',],
            ['kode_unit_audit' => '8106', 'nama_unit_audit' => 'INSPEKTORAT KAB. SERAM BAGIAN BARAT', 'jenis' => '0',],
            ['kode_unit_audit' => '8107', 'nama_unit_audit' => 'INSPEKTORAT KAB. KEPULAUAN ARU', 'jenis' => '0',],
            ['kode_unit_audit' => '8108', 'nama_unit_audit' => 'INSPEKTORAT KAB. MALUKU BARAT DAYA', 'jenis' => '0',],
            ['kode_unit_audit' => '8109', 'nama_unit_audit' => 'INSPEKTORAT KAB. BURU SELATAN', 'jenis' => '0',],
            ['kode_unit_audit' => '8171', 'nama_unit_audit' => 'INSPEKTORAT KOTA AMBON', 'jenis' => '0',],
            ['kode_unit_audit' => '8172', 'nama_unit_audit' => 'INSPEKTORAT KOTA TUAL', 'jenis' => '0',],
            ['kode_unit_audit' => '8200', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI MALUKU UTARA', 'jenis' => '1',],
            ['kode_unit_audit' => '8201', 'nama_unit_audit' => 'INSPEKTORAT KAB. HALMAHERA BARAT', 'jenis' => '0',],
            ['kode_unit_audit' => '8202', 'nama_unit_audit' => 'INSPEKTORAT KAB. HALMAHERA TENGAH', 'jenis' => '0',],
            ['kode_unit_audit' => '8203', 'nama_unit_audit' => 'INSPEKTORAT KAB. HALMAHERA UTARA', 'jenis' => '0',],
            ['kode_unit_audit' => '8204', 'nama_unit_audit' => 'INSPEKTORAT KAB. HALMAHERA SELATAN', 'jenis' => '0',],
            ['kode_unit_audit' => '8205', 'nama_unit_audit' => 'INSPEKTORAT KAB. KEPULAUAN SULA', 'jenis' => '0',],
            ['kode_unit_audit' => '8206', 'nama_unit_audit' => 'INSPEKTORAT KAB. HALMAHERA TIMUR', 'jenis' => '0',],
            ['kode_unit_audit' => '8207', 'nama_unit_audit' => 'INSPEKTORAT KAB. PULAU MOROTAI', 'jenis' => '0',],
            ['kode_unit_audit' => '8208', 'nama_unit_audit' => 'INSPEKTORAT KAB. PULAU TALIABU', 'jenis' => '0',],
            ['kode_unit_audit' => '8271', 'nama_unit_audit' => 'INSPEKTORAT KOTA TERNATE', 'jenis' => '0',],
            ['kode_unit_audit' => '8272', 'nama_unit_audit' => 'INSPEKTORAT KOTA TIDORE KEPULAUAN', 'jenis' => '0',],
            ['kode_unit_audit' => '9100', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI PAPUA', 'jenis' => '1',],
            ['kode_unit_audit' => '9101', 'nama_unit_audit' => 'INSPEKTORAT KAB. MERAUKE', 'jenis' => '0',],
            ['kode_unit_audit' => '9102', 'nama_unit_audit' => 'INSPEKTORAT KAB. JAYAWIJAYA', 'jenis' => '0',],
            ['kode_unit_audit' => '9103', 'nama_unit_audit' => 'INSPEKTORAT KAB. JAYAPURA', 'jenis' => '0',],
            ['kode_unit_audit' => '9104', 'nama_unit_audit' => 'INSPEKTORAT KAB. NABIRE', 'jenis' => '0',],
            ['kode_unit_audit' => '9105', 'nama_unit_audit' => 'INSPEKTORAT KAB. KEPULAUAN YAPEN', 'jenis' => '0',],
            ['kode_unit_audit' => '9106', 'nama_unit_audit' => 'INSPEKTORAT KAB. BIAK NUMFOR', 'jenis' => '0',],
            ['kode_unit_audit' => '9107', 'nama_unit_audit' => 'INSPEKTORAT KAB. PUNCAK JAYA', 'jenis' => '0',],
            ['kode_unit_audit' => '9108', 'nama_unit_audit' => 'INSPEKTORAT KAB. PANIAI', 'jenis' => '0',],
            ['kode_unit_audit' => '9109', 'nama_unit_audit' => 'INSPEKTORAT KAB. MIMIKA', 'jenis' => '0',],
            ['kode_unit_audit' => '9110', 'nama_unit_audit' => 'INSPEKTORAT KAB. SARMI', 'jenis' => '0',],
            ['kode_unit_audit' => '9111', 'nama_unit_audit' => 'INSPEKTORAT KAB. KEEROM', 'jenis' => '0',],
            ['kode_unit_audit' => '9112', 'nama_unit_audit' => 'INSPEKTORAT KAB. PEGUNUNGAN BINTANG', 'jenis' => '0',],
            ['kode_unit_audit' => '9113', 'nama_unit_audit' => 'INSPEKTORAT KAB. YAHUKIMO', 'jenis' => '0',],
            ['kode_unit_audit' => '9114', 'nama_unit_audit' => 'INSPEKTORAT KAB. TOLIKARA', 'jenis' => '0',],
            ['kode_unit_audit' => '9115', 'nama_unit_audit' => 'INSPEKTORAT KAB. WAROPEN', 'jenis' => '0',],
            ['kode_unit_audit' => '9116', 'nama_unit_audit' => 'INSPEKTORAT KAB. BOVEN DIGOEL', 'jenis' => '0',],
            ['kode_unit_audit' => '9117', 'nama_unit_audit' => 'INSPEKTORAT KAB. MAPPI', 'jenis' => '0',],
            ['kode_unit_audit' => '9118', 'nama_unit_audit' => 'INSPEKTORAT KAB. ASMAT', 'jenis' => '0',],
            ['kode_unit_audit' => '9119', 'nama_unit_audit' => 'INSPEKTORAT KAB. SUPIORI', 'jenis' => '0',],
            ['kode_unit_audit' => '9120', 'nama_unit_audit' => 'INSPEKTORAT KAB. MAMBERAMO RAYA', 'jenis' => '0',],
            ['kode_unit_audit' => '9121', 'nama_unit_audit' => 'INSPEKTORAT KAB. MAMBERAMO TENGAH', 'jenis' => '0',],
            ['kode_unit_audit' => '9122', 'nama_unit_audit' => 'INSPEKTORAT KAB. YALIMO', 'jenis' => '0',],
            ['kode_unit_audit' => '9123', 'nama_unit_audit' => 'INSPEKTORAT KAB. LANNY JAYA', 'jenis' => '0',],
            ['kode_unit_audit' => '9124', 'nama_unit_audit' => 'INSPEKTORAT KAB. NDUGA', 'jenis' => '0',],
            ['kode_unit_audit' => '9125', 'nama_unit_audit' => 'INSPEKTORAT KAB. PUNCAK', 'jenis' => '0',],
            ['kode_unit_audit' => '9126', 'nama_unit_audit' => 'INSPEKTORAT KAB. DOGIYAI', 'jenis' => '0',],
            ['kode_unit_audit' => '9127', 'nama_unit_audit' => 'INSPEKTORAT KAB. INTAN JAYA', 'jenis' => '0',],
            ['kode_unit_audit' => '9128', 'nama_unit_audit' => 'INSPEKTORAT KAB. DEIYAI', 'jenis' => '0',],
            ['kode_unit_audit' => '9171', 'nama_unit_audit' => 'INSPEKTORAT KOTA JAYAPURA', 'jenis' => '0',],
            ['kode_unit_audit' => '9200', 'nama_unit_audit' => 'INSPEKTORAT PROVINSI PAPUA BARAT', 'jenis' => '1',],
            ['kode_unit_audit' => '9201', 'nama_unit_audit' => 'INSPEKTORAT KAB. SORONG', 'jenis' => '0',],
            ['kode_unit_audit' => '9202', 'nama_unit_audit' => 'INSPEKTORAT KAB. MANOKWARI', 'jenis' => '0',],
            ['kode_unit_audit' => '9203', 'nama_unit_audit' => 'INSPEKTORAT KAB. FAK FAK', 'jenis' => '0',],
            ['kode_unit_audit' => '9204', 'nama_unit_audit' => 'INSPEKTORAT KAB. SORONG SELATAN', 'jenis' => '0',],
            ['kode_unit_audit' => '9205', 'nama_unit_audit' => 'INSPEKTORAT KAB. RAJA AMPAT', 'jenis' => '0',],
            ['kode_unit_audit' => '9206', 'nama_unit_audit' => 'INSPEKTORAT KAB. TELUK BINTUNI', 'jenis' => '0',],
            ['kode_unit_audit' => '9207', 'nama_unit_audit' => 'INSPEKTORAT KAB. TELUK WONDAMA', 'jenis' => '0',],
            ['kode_unit_audit' => '9208', 'nama_unit_audit' => 'INSPEKTORAT KAB. KAIMANA', 'jenis' => '0',],
            ['kode_unit_audit' => '9209', 'nama_unit_audit' => 'INSPEKTORAT KAB. TAMBRAUW', 'jenis' => '0',],
            ['kode_unit_audit' => '9210', 'nama_unit_audit' => 'INSPEKTORAT KAB. MAYBRAT', 'jenis' => '0',],
            ['kode_unit_audit' => '9211', 'nama_unit_audit' => 'INSPEKTORAT KAB. MANOKWARI SELATAN', 'jenis' => '0',],
            ['kode_unit_audit' => '9212', 'nama_unit_audit' => 'INSPEKTORAT KAB. PEGUNUNGAN ARFAK', 'jenis' => '0',],
            ['kode_unit_audit' => '9271', 'nama_unit_audit' => 'INSPEKTORAT KOTA SORONG', 'jenis' => '0',],
        ];

        // Ubah nama tabel sesuai dengan tabel yang digunakan
        $tableName = 'tr_kode_unit_audit';

        $chunkSize = 100; // Ukuran setiap batch

        // Membagi data ke dalam batch
        $chunks = array_chunk($data, $chunkSize);

        foreach ($chunks as $chunk) {
            // Memasukkan data ke dalam tabel dengan insert
            DB::table($tableName)->insert($chunk);
        }
    }
}
